# Utiliza una imagen base de Node.js
FROM node:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de paquete e instalalos
COPY package*.json ./
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Compila la aplicación de Angular
RUN npm run build

# Expone el puerto en el que se ejecutará la aplicación
EXPOSE 4200

# Inicia la aplicación cuando se ejecute el contenedor
CMD ["npm", "start"]
